// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkk3xSVSmmZ950coIin-PJYGwRwqLFBYU',
    appId: '1:34072149269:web:8d157407b0ef6f8234fd1c',
    messagingSenderId: '34072149269',
    projectId: 'careconnect-d4755',
    authDomain: 'careconnect-d4755.firebaseapp.com',
    storageBucket: 'careconnect-d4755.appspot.com',
    measurementId: 'G-J0KZ9NHPX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_asVtEb8WH4pYnggXv8T8Z6bu7jnRcM',
    appId: '1:34072149269:android:81f6a35c6140d92934fd1c',
    messagingSenderId: '34072149269',
    projectId: 'careconnect-d4755',
    storageBucket: 'careconnect-d4755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCvEVLtdmMRJn0Dn1u5OXqbpGX4uGLik',
    appId: '1:34072149269:ios:26b0b89bf5b9a14934fd1c',
    messagingSenderId: '34072149269',
    projectId: 'careconnect-d4755',
    storageBucket: 'careconnect-d4755.appspot.com',
    iosBundleId: 'com.example.orphanagemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCvEVLtdmMRJn0Dn1u5OXqbpGX4uGLik',
    appId: '1:34072149269:ios:84e829b96231728b34fd1c',
    messagingSenderId: '34072149269',
    projectId: 'careconnect-d4755',
    storageBucket: 'careconnect-d4755.appspot.com',
    iosBundleId: 'com.example.orphanagemanagement.RunnerTests',
  );
}
